import { Phone, Gift, Calendar } from "lucide-react";
import FeatureCard from "../ui/FeatureCard";

export default function FeaturesSection() {
  const features = [
    {
      icon: <Phone className="w-8 h-8 text-white" />,
      title: "AI Voice Reminders",
      description: "Receive personalized voice calls reminding you of upcoming birthdays with custom messages generated by AI.",
      iconBgColor: "bg-gray-800"
    },
    {
      icon: <Gift className="w-8 h-8 text-white" />,
      title: "Smart Gift Ideas", 
      description: "Get personalized gift recommendations powered by Google's Gemini AI based on your friends' interests.",
      iconBgColor: "bg-gray-800"
    },
    {
      icon: <Calendar className="w-8 h-8 text-white" />,
      title: "Smart Scheduling",
      description: "Automatically schedule reminders days or weeks before birthdays so you never miss an important date.",
      iconBgColor: "bg-gray-800"
    }
  ];

  return (
    <div className="py-16 sm:py-24">
      {/* Section Header */}
      <div className="text-center mb-16">
        <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">A game-changer for celebrations</h2>
        <p className="text-lg text-gray-300 max-w-2xl mx-auto leading-relaxed">
          Birthday managers, event planners, busy professionals - of all levels - are using WishLoop to never miss important dates.
        </p>
      </div>
      
      {/* Features Grid */}
      <div className="grid md:grid-cols-3 gap-8 lg:gap-12">
        {features.map((feature, index) => (
          <FeatureCard
            key={index}
            icon={feature.icon}
            title={feature.title}
            description={feature.description}
            iconBgColor={feature.iconBgColor}
          />
        ))}
      </div>
    </div>
  );
}
